# 主题
theme:
  switch: true
  default: style-light # style-light style-dark

# 网站图标
favicon:
  logo: /img/icon.jpg
  icon16: /img/icon.jpg
  icon32: /img/icon.jpg
  apple_touch_icon: /img/icon.jpg
  visibilitychange: true
  hidden: failure.ico
  show_text: (ง •_•)ง 你好呀！
  hide_text: (o゜▽゜)o 再见！

# 导航栏
top_bars:
  - title: menu.home
    url: /
  - title: 分类
    url: /categories/
  - title: 标签
    url: /tags/
  - title: menu.archives
    url: /archives/
  - title: menu.about
    url: /about/
  - title: 相册
    url: /gallery/


banner:
  use_cover: false # Use the cover image for article details | 文章详情使用封面图
  danmu: # danmu | 弹幕
    enable: false # enable | 启用
    el: .trm-banner # el | 弹幕容器
  index: ## 首页横幅
    type: video
    bgurl: https://cdn.moji.com/websrc/video/video621.mp4
    banner_title: 灵魂的渴望是命运的先知。
    banner_text: Hi my new friend!
  category: ## 归档页横幅
    type: video
    bgurl: https://cdn.moji.com/websrc/video/winter20181129.mp4
    banner_title: 云间连下榻，<br>天上接行杯。
    banner_text: The article categories
  tag:
    type: video
    bgurl: https://cdn.moji.com/websrc/video/spring20190320.mp4
    banner_title: 醉后不知天在水，<br>满船清梦压星河。
    banner_text: The article tags 
  archive:
    type: video
    bgurl: https://cdn.moji.com/websrc/video/video.mp4
    banner_title: 树深时见鹿，<br>溪午不闻钟。
    banner_text: The article archive


# 侧边栏
sidebar:
  typed_text_prefix: I`m
  typed_text: ["多模态算法工程师","机器人狂热爱好者","UE5游戏设计师","三年全栈软件开发工作经验"]
  info: # 个人信息
    - key: ADDRESS
      val: 悉尼
    - key: UNIVERSITY
      val: 新南威尔士大学
    - key: MAJOR
      val: 硕士-信息技术-人工智能
    - key: AGE
      val: 26
  social: # 社交地址
    - name: github
      icon: fab fa-github
      url: https://github.com/caijinhong1999
    - name: gitee
      icon: fas fa-code-branch
      url: https://gitee.com/caijinhong1999
    - name: email
      icon: fas fa-envelope
      url: mailto:cjh18242065873@163.com
    - name: wechat
      icon: fab fa-weixin
      url: /img/wx.jpg
    - name: qq
      icon: fab fa-qq
      url: /img/qq.jpg
    

# 用户信息
user:
  name: Jessie
  first_name: Jinhong
  last_name: CAI
  email: cjh18242065873@163.com
  domain: https://jinhongcai.work
  avatar: /img/cjh.jpg
  describe: 多模态算法工程师 | 机器人爱好者 | 开源爱好者 | 电子产品DIY爱好者
  rule_text: 本站所有文章除特别声明外，均采用 CC BY-NC-SA 4.0 许可协议。转载请注明出处！

# 评论系统所需的第三方脚本（让主题能加载 twikoo）
assets:
  internal_provider: unpkg
  third_party_provider: jsdelivr
  plugin:
    # 用主题默认路径即可；要锁新版也可改成 1.6.38
    twikoo: /twikoo@1.6.7/dist/twikoo.all.min.js

# 页脚
footer:
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 10/10/2025 00:00:00

# ！！！关键：只启用 twikoo，彻底禁用 bComments
comment:
  enable: true            # 有些版本有这个总开关，写上更稳
  type: twikoo            # 如果你的主题支持 type/use，写上它，强制选择 twikoo
  twikoo:
    enable: true
    envId: https://comment.jinhongcai.work
  bComments:
    enable: false         # ← 必须为 false，或直接把 bComments 这段删掉


# 站内搜索
search:
  enable: true
  type: engine  # engine
  href: 'https://www.google.com/search?q=site:'
  # href: "https://www.baidu.com/s?wd=site:"
  # href: "https://www.bing.com/search?q=site:"
  domain: www.jinhongcai.work
  
# SEO 设置
baidu_push: true

